// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportNote(arg1, arg2) {
  return window['go']['main']['App']['ExportNote'](arg1, arg2);
}

export function ImportFiles(arg1) {
  return window['go']['main']['App']['ImportFiles'](arg1);
}

export function ImportNote() {
  return window['go']['main']['App']['ImportNote']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function RenderD2(arg1) {
  return window['go']['main']['App']['RenderD2'](arg1);
}
