// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportNote(arg1:string,arg2:string):Promise<string>;

export function ImportFiles(arg1:Array<string>):Promise<Array<main.Note>>;

export function ImportNote():Promise<Array<main.Note>>;

export function OpenURL(arg1:string):Promise<void>;

export function RenderD2(arg1:string):Promise<string>;
