// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateNote(arg1:string,arg2:string,arg3:Array<string>):Promise<main.Note>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetNote(arg1:string):Promise<main.Note>;

export function ListNotes():Promise<Array<main.NoteMeta>>;

export function ListTags():Promise<Array<string>>;

export function SearchNotes(arg1:string):Promise<Array<main.NoteMeta>>;

export function UpdateNote(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<main.Note>;
