// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateImported(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['NoteService']['CreateImported'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNote(arg1, arg2, arg3) {
  return window['go']['main']['NoteService']['CreateNote'](arg1, arg2, arg3);
}

export function DeleteNote(arg1) {
  return window['go']['main']['NoteService']['DeleteNote'](arg1);
}

export function GetNote(arg1) {
  return window['go']['main']['NoteService']['GetNote'](arg1);
}

export function ListNotes() {
  return window['go']['main']['NoteService']['ListNotes']();
}

export function ListTags() {
  return window['go']['main']['NoteService']['ListTags']();
}

export function SearchNotes(arg1) {
  return window['go']['main']['NoteService']['SearchNotes'](arg1);
}

export function UpdateNote(arg1, arg2, arg3, arg4) {
  return window['go']['main']['NoteService']['UpdateNote'](arg1, arg2, arg3, arg4);
}
